/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.matrixpeckham.jdoom;

/**
 *
 * @author matri
 */
public class SoundEnum {

    public static final int //java enum can't be used as index
            sfx_None = 0,
            sfx_pistol = 1,
            sfx_shotgn = 2,
            sfx_sgcock = 3,
            sfx_dshtgn = 4,
            sfx_dbopn = 5,
            sfx_dbcls = 6,
            sfx_dbload = 7,
            sfx_plasma = 8,
            sfx_bfg = 9,
            sfx_sawup = 10,
            sfx_sawidl = 11,
            sfx_sawful = 12,
            sfx_sawhit = 13,
            sfx_rlaunc = 14,
            sfx_rxplod = 15,
            sfx_firsht = 16,
            sfx_firxpl = 17,
            sfx_pstart = 18,
            sfx_pstop = 19,
            sfx_doropn = 20,
            sfx_dorcls = 21,
            sfx_stnmov = 22,
            sfx_swtchn = 23,
            sfx_swtchx = 24,
            sfx_plpain = 25,
            sfx_dmpain = 26,
            sfx_popain = 27,
            sfx_vipain = 28,
            sfx_mnpain = 29,
            sfx_pepain = 30,
            sfx_slop = 31,
            sfx_itemup = 32,
            sfx_wpnup = 33,
            sfx_oof = 34,
            sfx_telept = 35,
            sfx_posit1 = 36,
            sfx_posit2 = 37,
            sfx_posit3 = 38,
            sfx_bgsit1 = 39,
            sfx_bgsit2 = 40,
            sfx_sgtsit = 41,
            sfx_cacsit = 42,
            sfx_brssit = 43,
            sfx_cybsit = 44,
            sfx_spisit = 45,
            sfx_bspsit = 46,
            sfx_kntsit = 47,
            sfx_vilsit = 48,
            sfx_mansit = 49,
            sfx_pesit = 50,
            sfx_sklatk = 51,
            sfx_sgtatk = 52,
            sfx_skepch = 53,
            sfx_vilatk = 54,
            sfx_claw = 55,
            sfx_skeswg = 56,
            sfx_pldeth = 57,
            sfx_pdiehi = 58,
            sfx_podth1 = 59,
            sfx_podth2 = 60,
            sfx_podth3 = 61,
            sfx_bgdth1 = 62,
            sfx_bgdth2 = 63,
            sfx_sgtdth = 64,
            sfx_cacdth = 65,
            sfx_skldth = 66,
            sfx_brsdth = 67,
            sfx_cybdth = 68,
            sfx_spidth = 69,
            sfx_bspdth = 70,
            sfx_vildth = 71,
            sfx_kntdth = 72,
            sfx_pedth = 73,
            sfx_skedth = 74,
            sfx_posact = 75,
            sfx_bgact = 76,
            sfx_dmact = 77,
            sfx_bspact = 78,
            sfx_bspwlk = 79,
            sfx_vilact = 80,
            sfx_noway = 81,
            sfx_barexp = 82,
            sfx_punch = 83,
            sfx_hoof = 84,
            sfx_metal = 85,
            sfx_chgun = 86,
            sfx_tink = 87,
            sfx_bdopn = 88,
            sfx_bdcls = 89,
            sfx_itmbk = 90,
            sfx_flame = 91,
            sfx_flamst = 92,
            sfx_getpow = 93,
            sfx_bospit = 94,
            sfx_boscub = 95,
            sfx_bossit = 96,
            sfx_bospn = 97,
            sfx_bosdth = 98,
            sfx_manatk = 99,
            sfx_mandth = 100,
            sfx_sssit = 101,
            sfx_ssdth = 102,
            sfx_keenpn = 103,
            sfx_keendt = 104,
            sfx_skeact = 105,
            sfx_skesit = 106,
            sfx_skeatk = 107,
            sfx_radio = 108,
            NUMSFX = 109;

}
